name: ColorfulArmor
version: 1.5
main: Enes5519\colorfularmor\ColorfulArmor
api: [3.0.0-ALPHA5, 3.0.0, 4.0.0]
author: Enes5519

permissions:
  enes5519.colorfularmor:
    default: op
    description: ColorfulArmor Permission